### ISSUE TITLE
cpuinfo显示问题

### ISSUE THREAD

**Issue by linclin** [chenchun/cgroupfs#3]
container_id=`docker create -v /tmp/cgroupfs/meminfo:/proc/meminfo -v/tmp/cgroupfs/cpuinfo:/proc/cpuinfo  --cpu-period 100000 --cpu-quota 200000  --memory 15m  --memory-swap 15m  ubuntu sleep 213133`
meminfo显示容器分配内存正确,cpuinfo显示还是宿主机,如何显示正确分配的cpu信息

**Comment by chenchun** [comment]
因为cpuinfo的某些数据并不能从cgroup中得到
